"""create users Lojas

Revision ID: ae7a218e92df
Revises: 6b93f9b0f083
Create Date: 2026-02-20 21:45:09.161240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae7a218e92df'
down_revision: Union[str, Sequence[str], None] = '6b93f9b0f083'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('endereco',
    sa.Column('idendereço', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rua', sa.String(length=15), nullable=False),
    sa.Column('numero', sa.String(length=15), nullable=True),
    sa.Column('bairro', sa.String(length=45), nullable=True),
    sa.Column('cidade_estado', sa.String(length=45), nullable=True),
    sa.Column('idcliente', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idcliente'], ['cliente.idcliente'], ),
    sa.PrimaryKeyConstraint('idendereço')
    )
    op.add_column('cliente', sa.Column('idcliente', sa.Integer(), nullable=False))
    op.drop_column('cliente', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cliente', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('cliente', 'idcliente')
    op.drop_table('endereco')
    # ### end Alembic commands ###
